# Generated by Django 5.1.7 on 2025-03-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalpackage',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='standardpackage',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='starterpackage',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
