# Generated by Django 5.1.7 on 2025-03-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_packages', '0002_alter_professionalpackage_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalpackage',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='standardpackage',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='starterpackage',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
