# Generated by Django 5.1.4 on 2025-04-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_packages', '0004_agentspackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('package_content', models.CharField(blank=True, max_length=255, null=True)),
                ('package_price', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
