# Generated by Django 5.1.7 on 2025-04-17 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_packages', '0005_agentscard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentscard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi '),
        ),
        migrations.AlterField(
            model_name='agentscard',
            name='package_content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cart İçeriği '),
        ),
        migrations.AlterField(
            model_name='agentscard',
            name='package_name',
            field=models.CharField(max_length=255, verbose_name='Cart Adı '),
        ),
        migrations.AlterField(
            model_name='agentscard',
            name='package_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cart Etiket Fiyatı '),
        ),
        migrations.AlterField(
            model_name='agentspackage',
            name='feature_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ajan Özellik 1 '),
        ),
        migrations.AlterField(
            model_name='agentspackage',
            name='feature_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ajan Özellik 1 '),
        ),
        migrations.AlterField(
            model_name='agentspackage',
            name='feature_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ajan Özellik 1 '),
        ),
        migrations.AlterField(
            model_name='agentspackage',
            name='feature_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ajan Özellik 1 '),
        ),
        migrations.AlterField(
            model_name='agentspackage',
            name='feature_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ajan Özellik 1 '),
        ),
        migrations.AlterField(
            model_name='agentspackage',
            name='feature_6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ajan Özellik 1 '),
        ),
        migrations.AlterField(
            model_name='agentspackage',
            name='package_duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ajan  Paket Süresi '),
        ),
        migrations.AlterField(
            model_name='agentspackage',
            name='package_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_packages.agentscard', verbose_name='Ajan Paket Adı '),
        ),
        migrations.AlterField(
            model_name='agentspackage',
            name='package_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ajan Fiyatı '),
        ),
    ]
