# Generated by Django 5.1.7 on 2025-04-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_packages', '0006_alter_agentscard_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentspackage',
            name='package_content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kısa İçerik '),
        ),
        migrations.AlterField(
            model_name='agentscard',
            name='package_price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cart Etiket Fiyatı '),
        ),
    ]
