# Generated by Django 5.1.7 on 2025-04-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_packages', '0007_agentspackage_package_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentspackage',
            name='package_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ajan Başlık '),
        ),
        migrations.AlterField(
            model_name='agentspackage',
            name='package_content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ajan Kısa İçerik '),
        ),
    ]
