# Generated by Django 5.1.7 on 2025-04-18 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_packages', '0009_agentspayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentspayment',
            options={'verbose_name': 'Agents Ödemesi', 'verbose_name_plural': 'Agents Ödemeleri'},
        ),
        migrations.AlterField(
            model_name='agentspayment',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='agentspayment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='agentspayment',
            name='package_id',
            field=models.IntegerField(verbose_name='Paket ID'),
        ),
        migrations.AlterField(
            model_name='agentspayment',
            name='package_name',
            field=models.CharField(max_length=255, verbose_name='Paket Adı (ID)'),
        ),
        migrations.AlterField(
            model_name='agentspayment',
            name='package_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Paket Fiyatı'),
        ),
        migrations.AlterField(
            model_name='agentspayment',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Satın Alma Tarihi'),
        ),
        migrations.AlterField(
            model_name='agentspayment',
            name='purchased_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Satın Alan Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='agentspayment',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Kullanıcı E-posta'),
        ),
        migrations.AlterField(
            model_name='agentspayment',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kullanıcının Tam Adı'),
        ),
    ]
