# Generated by Django 5.1.7 on 2025-04-18 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_packages', '0010_alter_agentspayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentspackage',
            name='package_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentscard', to='product_packages.agentscard', verbose_name='Ajan Paket Adı '),
        ),
    ]
