# Generated by Django 5.1.7 on 2025-04-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_packages', '0011_alter_agentspackage_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentspayment',
            name='agents_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ajan ID'),
        ),
        migrations.AddField(
            model_name='agentspayment',
            name='agents_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ajan Adı (ID)'),
        ),
        migrations.AlterField(
            model_name='agentspayment',
            name='package_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Paket ID'),
        ),
        migrations.AlterField(
            model_name='agentspayment',
            name='package_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paket Adı (ID)'),
        ),
    ]
