# Generated by Django 5.1.7 on 2025-04-22 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAgents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('system_prompt', models.TextField()),
                ('user_prompt', models.TextField()),
                ('image1', models.ImageField(upload_to='instagram_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='instagram_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='instagram_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='instagram_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='instagram_images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='instagram_images/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='instagram_images/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='instagram_images/')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='instagram_images/')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='instagram_images/')),
                ('captions', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('hashtag', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time1', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_time2', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_time3', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_time4', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_time5', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_time6', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_time7', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_time8', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_time9', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_time10', models.CharField(blank=True, max_length=100, null=True)),
                ('post_frequency', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
