# Generated by Django 5.1.7 on 2025-04-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramagents',
            name='system_prompt',
        ),
        migrations.RemoveField(
            model_name='instagramagents',
            name='user_prompt',
        ),
    ]
