# Generated by Django 5.1.7 on 2025-04-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistan', '0002_remove_instagramagents_system_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramagents',
            name='system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramagents',
            name='user_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
