# Generated by Django 5.1.4 on 2025-04-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistan', '0003_instagramagents_system_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramagents',
            name='image_prompt_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
