# Generated by Django 5.1.4 on 2025-04-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistan', '0004_instagramagents_image_prompt_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramagents',
            name='captions',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='instagramagents',
            name='hashtag',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
